sudo: required
services:
  - docker

before_install:
  - docker build -t multi-docker/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run multi-docker/react-test npm test -- --coverage

after_success:
  - docker build -t multi-docker/multi-client ./client
  - docker build -t multi-docker/multi-nginx ./nginx
  - docker build -t multi-docker/multi-server ./server
  - docker build -t multi-docker/multi-worker ./worker
  # log in to the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --passowrd-stdin
  # Take those images and push them to docker hub 
  - docker push multi-docker/multi-client
  - docker push multi-docker/multi-nginx
  - docker push multi-docker/multi-server
  - docker push multi-docker/multi-worker
