sudo: required
services:
  - docker

before_install:
  - docker build -t haseemsaeed1/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run haseemsaeed1/react-test npm test -- --coverage

after_success:
  - docker build -t haseemsaeed1/multi-client ./client
  - docker build -t haseemsaeed1/multi-nginx ./nginx
  - docker build -t haseemsaeed1/multi-server ./server
  - docker build -t haseemsaeed1/multi-worker ./worker
  # log in to the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub 
  - docker push haseemsaeed1/multi-client
  - docker push haseemsaeed1/multi-nginx
  - docker push haseemsaeed1/multi-server
  - docker push haseemsaeed1/multi-worker
